### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by jlambert121**
Update packages to latest versions to work compiling with newer versions of node.

### CODE REVIEW

**Comment by pkissling** [comment]
thank you for the Par. will have a look after my vacation mid january

**Review by pkissling — CHANGES_REQUESTED** [review]
i am not able to run `rollup --watch` (`yarn start`). due to the following error:
```
bundles src/clock-weather-card.ts → dist...
[!] (plugin rpt2) RollupError: ENOENT: no such file or directory, open '/home/pi/clock-weather-card/node_modules/.cache/rollup-plugin-typescript2/rpt2_18c7dc991f63efb0dd8d2c0c5d580b2ae135182f/code/cache_/4518e905b9d18222ab3afd368af3b42567fa5f00'
```
does it work for you?

**Comment by jlambert121** [comment]
Honestly I don't do JS/TS development at all so am not sure how to get `rollup` going.... I tested this by rebuilding this with my other PR and it's working locally.  I can try to dig into it more this weekend though.

**Comment by pkissling** [comment]
Nevermind. if you are not able to fix it with little effort, i will have a look at it myself some day.
i wanted to update the dependencies anyways.  might be that i even get rid of rollup and lit in the first place.

**Pull request closed without merging**
